# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json


# Import API key
from config import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
path="../WeatherPy/output_data/cities.csv"
cities_df=pd.read_csv(path)
cities_df.head()

,Unnamed: 0,City,Country,Temperature,Latitude,Longitude,Wind Speed,Humidity,Cloudiness,Date
0,0,avarua,CK,80.6,-21.21,-159.78,6.93,83,67,1599869900
1,1,petropavlovsk-kamchatskiy,RU,55.4,53.05,158.65,4.47,82,20,1599870039
2,2,sao jose dos pinhais,BR,77.0,-25.53,-49.21,5.82,61,100,1599870040
3,3,la asuncion,VE,93.2,11.03,-63.86,6.93,52,12,1599870040
4,4,hobart,AU,53.6,-42.88,147.33,5.82,66,40,1599869951

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)
locations = cities_df[["Latitude", "Longitude"]]
humidity=cities_df["Humidity"].astype(float)

In [4]:
fig=gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)

# Add layer
fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
perfect_weather_df= cities_df.loc[(cities_df["Wind Speed"]<10) & (cities_df["Cloudiness"]==0) & (cities_df["Temperature"]>70) & (cities_df["Temperature"]<80)]
perfect_weather_df.drop('Unnamed: 0',axis='columns', inplace=True)
perfect_weather_df.dropna(how="any")

C:\Users\luisg\AppData\Roaming\Python\Python38\site-packages\pandas\core\frame.py:4160: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,City,Country,Temperature,Latitude,Longitude,Wind Speed,Humidity,Cloudiness,Date
80,awjilah,LY,75.54,29.11,21.29,9.46,58,0,1599870075
111,bania,RO,75.00,44.90,22.04,1.12,72,0,1599870098
131,marsa matruh,EG,77.00,31.35,27.25,5.12,65,0,1599870020
146,cacu,BR,77.68,-18.56,-51.13,3.67,18,0,1599870122
193,yulara,AU,73.40,-25.24,130.99,8.05,27,0,1599870143
218,port augusta,AU,73.99,-32.50,137.77,6.93,87,0,1599870153
237,bardiyah,LY,74.52,31.76,25.09,9.64,83,0,1599870164
244,caravelas,BR,72.50,-17.71,-39.25,7.65,82,0,1599870033
338,alice springs,AU,77.00,-23.70,133.88,9.17,22,0,1599870125
358,milos,GR,73.40,36.75,24.43,3.36,73,0,1599870243
363,centralina,BR,77.68,-18.58,-49.20,6.08,24,0,1599870250
379,corinto,GR,73.99,37.94,22.96,1.01,44,0,1599870258
415,port hedland,AU,75.20,-20.32,118.57,5.82,60,0,1599870282
541,esmeraldas,BR,77.00,-19.76,-44.31,3.36,33,0,1599870367
544,jalu,LY,75.49,29.03,21.55,8.34,58,0,1599870369

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
hotel_df=perfect_weather_df
hotel_df["Hotel Name"]=""
hotel_df.head()

<ipython-input-6-07d6a7fd820d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df["Hotel Name"]=""

,City,Country,Temperature,Latitude,Longitude,Wind Speed,Humidity,Cloudiness,Date,Hotel Name
80,awjilah,LY,75.54,29.11,21.29,9.46,58,0,1599870075,
111,bania,RO,75.00,44.90,22.04,1.12,72,0,1599870098,
131,marsa matruh,EG,77.00,31.35,27.25,5.12,65,0,1599870020,
146,cacu,BR,77.68,-18.56,-51.13,3.67,18,0,1599870122,
193,yulara,AU,73.40,-25.24,130.99,8.05,27,0,1599870143,

In [7]:
params = {
    "radius": 5000    ,
    "types": "lodging",
    "keyword": "Hotel",
    "key": g_key
}

for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Latitude"]
    lng = row["Longitude"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Use the search term: "International Airport" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)
    
#     print the name_address url, avoid doing for public github repos in order to avoid exposing key
#     print(name_address.url)

    # convert to json
    name_address = name_address.json()
    # print(json.dumps(name_address, indent=4, sort_keys=True))

    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address["results"][0]["name"]
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

Missing field/result... skipping.

C:\Users\luisg\AppData\Roaming\Python\Python38\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [8]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]
humidity=hotel_df["Humidity"].astype(float)

In [11]:
# Add marker layer ontop of heat map
fig = gmaps.figure()
markers =gmaps.marker_layer(
    locations,
    info_box_content=hotel_info
)

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)

# Add layer
fig.add_layer(heat_layer)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))